version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: video_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: change to a strong password
      POSTGRES_DB: video_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - video_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: ghcr.io/seqcrafter/zyfun-danmu:1.0.0
    container_name: video_api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: same as the one in the postgres service
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: video_database
      API_BASE_URL: http://localhost:7768/api/v1/<API_KEY>
    ports:
      - "8080:8080"
    networks:
      - video_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  video_network:
    driver: bridge
